#!/usr/bin/env python3

from sys import argv
from os import path

if __name__ == "__main__":
    if len(argv) != 3:
        print("Usage: " + path.basename(__file__) + " filename tag")
        exit(1)

    filename = argv[1] + ".test.cpp"
    if path.isfile(filename):
        print("Error: file(%s) already exists" % (filename))
        exit(1)
    
    with open(filename, 'w') as output:
        output.write('#include "catch.hpp"\n')
        output.write('#include "./%s.hpp"\n\n' % (argv[1]))
        output.write('TEST_CASE("%s", "[%s]") {\n' % (argv[1], argv[2]))
        output.write('}\n')

