#!/usr/bin/env python3

from sys import argv
from os import path

if __name__ == "__main__":
    if len(argv) != 3:
        print("Usage: " + path.basename(__file__) + " filename tag")
        exit(1)

    cppName = argv[1] + ".test.cpp"
    hppName = argv[1] + ".test.hpp"

    if path.isfile(cppName):
        print("Error: file(%s) already exists" % (cppName))
        exit(1)
    
    if path.isfile(hppName):
        print("Error: file(%s) already exists" % (hppName))
        exit(1)

    with open(hppName, 'w') as output:
        output.write('#include "catch.hpp"\n')
        output.write('#include "%s.hpp"\n\n' % (argv[1]))

    with open(cppName, 'w') as output:
        output.write('#include "./%s"\n\n' % (hppName))
        output.write('TEST_CASE("%s", "[%s]") {\n' % (argv[1], argv[2]))
        output.write('}\n')


